# Generated by Django 2.1.1 on 2018-11-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='opt_in_to_rewards',
            field=models.BooleanField(default=True),
        ),
    ]
