# Generated by Django 2.1.1 on 2018-11-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
