# Generated by Django 2.1.1 on 2019-01-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190123_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voter_count',
            field=models.IntegerField(default=0),
        ),
    ]
