# Generated by Django 2.1.1 on 2019-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_voter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='promotion_amount',
            field=models.FloatField(blank=True, help_text='Promotion amount in SBD', null=True),
        ),
    ]
