# Generated by Django 2.1.1 on 2019-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_promotiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontransaction',
            name='trx_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
