# Generated by Django 2.1.1 on 2019-01-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_promotiontransaction_trx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontransaction',
            name='memo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
