# Generated by Django 2.1.1 on 2019-01-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_promotiontransaction_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiontransaction',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotiontransaction',
            name='permlink',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
