# Generated by Django 2.1.1 on 2019-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190125_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontransaction',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotiontransaction',
            name='from_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotiontransaction',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotiontransaction',
            name='permlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
