# Generated by Django 2.1.1 on 2019-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190125_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontransaction',
            name='from_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
