# Generated by Django 2.1.1 on 2019-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_voteaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteaudit',
            name='choice',
        ),
        migrations.AddField(
            model_name='voteaudit',
            name='choices',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
    ]
