# Generated by Django 2.1.1 on 2019-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteaudit',
            name='choices',
            field=models.ManyToManyField(blank=True, to='polls.Choice'),
        ),
    ]
