# Generated by Django 2.1.1 on 2019-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190205_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=64, null=True),
        ),
    ]
